server:
   port: 12001
#数据库配置
spring:
   datasource:
      username: work
      password: N3TGSQX2XNicYVdO3aVE
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.23:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  
#mybatis配置
mybatis:
  typeAliasesPackage: com.example.model
  mapperLocations: classpath:mapper/*.xml
#xxl-job 任务调度中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list：调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
      addresses: http://127.0.0.1:10000/xxl-job-admin
    executor:
      ### xxl-job executor address：执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据；地址信息用于"调度中心请求并触发任务"和"执行器注册"。
      ### 执行器默认端口为9999，执行器IP默认为空表示自动获取IP，多网卡时可手动设置指定IP，手动设置IP时将会绑定Host。单机部署多个执行器时，注意要配置不同执行器端口；
      appName: task-executor
      ip: 127.0.0.1
      port: 10001
      ### xxl-job log path：执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logPath: /logs/task-executor/jobhandler
      ### xxl-job log retention days：执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
      logRetentionDays: -1
    ### xxl-job, access token：执行器通讯TOKEN，非空时启用
    accessToken: