spring:
   application:
      name: rokcetmq-demo
server:
   port: 13001

# rocket 配置
rocketmq:
   # 生产者配置
   producer:
      groupName: ${spring.application.name}
      nameSrvAddr: 127.0.0.1:9876
      default: true
   # 消费者配置
   consumer:
      groupName: ${spring.application.name}
      nameSrvAddr: 127.0.0.1:9876