server:
   port: 8088
#数据库配置
spring:
   datasource:
      username: work
      password: N3TGSQX2XNicYVdO3aVE
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.23:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  
#mybatis配置
mybatis:
  typeAliasesPackage: com.example.model
  mapperLocations: classpath:mapper/*.xml